# name: Deploy Laravel to Hostinger

# on:
#   push:
#     branches:
#       - dev
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 22

#       - name: Install Node Dependencies
#         run: npm install

#       - name: Build Frontend
#         run: npm run build

#       - name: Deploy via FTP
#         uses: SamKirkland/FTP-Deploy-Action@v4
#         with:
#           server: ${{ secrets.FTP_Server }}
#           username: ${{ secrets.FTP_Username }}
#           password: ${{ secrets.FTP_Password }}
#           server-dir: public_html/
